[package]
name = "analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.0"
num = "0.4.1"
ssca-sys = { version = "0.1.0", path = "../ssca-sys" }
