[package]
name = "ssca-sys"
version = "0.1.0"
edition = "2021"
links = "analyzer_native"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc.workspace = true

[dependencies]
cc.workspace = true
num.workspace = true
